version: 2
jobs:
  build:
    working_directory: ~/ruslingdkbot
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: yarn-cache-{{ checksum "RusBot/package.json" }}
      - run:
          name: Run Yarn install
          command: cd RusBot && yarn install
      - save_cache:
          key: yarn-cache-{{ checksum "RusBot/package.json" }}
          paths:
            - ./node_modules
            - ./RusBot/node_modules
      - run:
          name: Setup Config
          command: cd RusBot && cp config.example.json config.json
      - run:
          name: Run ESLint
          command: cd RusBot && yarn eslint
      - run:
          name: Build container
          command: |
            docker-compose build
      # TODO: Run Specs


workflows:
  version: 2
  build_container:
    jobs:
      - build
      # - test:
      #   requires:
      #     - build
      #   filters:
      #     branches:
      #       only: master
