version: 2
jobs:
  build:
    working_directory: ~/ruslingdkbot
    docker:
      - image: circleci/node:9.9
    steps:
      - checkout
      - restore_cache:
          key: yarn-cache-{{ checksum "RusBot/package.json" }}
      - run:
          name: Run Yarn install
          command: yarn install
      - save_cache:
          key: yarn-cache-{{ checksum "RusBot/package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run ESLint
          command: yarn eslint
      # TODO: Run Specs
